// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhoixxcgwszdteopvhgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impob2l4eGNnd3N6ZHRlb3B2aGdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTk2ODQsImV4cCI6MjA3NDM3NTY4NH0.v_FrgY_IRgLCuuzUqWUJP_JuGvhg_gz2Ufax48JuDVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});